### PR TITLE
fastqc: fix build and startup when default java is too old

### LINKED ISSUE #130: [BUG] FastQC AUR build fails
This is regarding the [fastq AUR](https://aur.archlinux.org/packages/fastqc) which is based on the following file and is maintained by @starsareintherose :

https://github.com/BioArchLinux/Packages/blob/master/BioArchLinux/fastqc/PKGBUILD

While updating the fastQC AUR, I got the following error. I believe it is bevause the `javac -target` should be `1.8` instead of `11` which is [defined in the `build.xml`](https://github.com/s-andrews/FastQC/blob/d4f2e91d67b765867b59cde3c6a9a6c7de34ae37/build.xml#L10). The following is verbatim from the `man javac`:

> ```
>        -target version
>               Generates class files that target a specified release of the virtual machine. Class files will
>               run on the specified target and on later releases, but not on earlier releases of the JVM.
>               Valid targets are 1.1, 1.2, 1.3, 1.4, 1.5 (also 5), 1.6 (also 6), 1.7 (also 7), and 1.8 (also 8).
>               The default for the -target option depends on the value of the -source option:
>               
>               • If the -source option is not specified, then the value of the -target option is 1.8
>               • If the -source option is 1.2, then the value of the -target option is 1.4
>               • If the -source option is 1.3, then the value of the -target option is 1.4
>               • If the -source option is 1.5, then the value of the -target option is 1.8
>               • If the -source option is 1.6, then the value of the -target is option 1.8
>               • If the -source option is 1.7, then the value of the -target is option 1.8
>               • For all other values of the -source option, the value of the -target option is the value
>                 of the -source option.
> ```

This means we have to patch the `build.xml` during the AURs `prepare` function to replace the following lines to have the correct value:

https://github.com/s-andrews/FastQC/blob/d4f2e91d67b765867b59cde3c6a9a6c7de34ae37/build.xml#L10-L11

**Log of the bug**

<details><summary>My terminal output</summary>

```console
❯  paru
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
:: Starting full system upgrade...
warning: r: ignoring package upgrade (4.0.3-2 => 4.2.3-1)
 there is nothing to do
:: Looking for AUR upgrades...
:: Looking for devel upgrades...
:: Resolving dependencies...
:: Calculating conflicts...
:: Calculating inner conflicts...

Aur (1) fastqc-0.12.1-2

:: Proceed to review? [Y/n]: y

:: Downloading PKGBUILDs...
 PKGBUILDs up to date
 nothing new to review
fetching devel info...
==> Making package: fastqc 0.12.1-2 (Wed 26 Apr 2023 10:47:14 AM EEST)
==> Retrieving sources...
  -> Found fastqc-0.12.1
  -> Found fastqc.patch
==> Validating source files with md5sums...
    fastqc-0.12.1 ... Passed
    fastqc.patch ... Passed
==> Making package: fastqc 0.12.1-2 (Wed 26 Apr 2023 10:47:15 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found fastqc-0.12.1
  -> Found fastqc.patch
==> Validating source files with md5sums...
    fastqc-0.12.1 ... Passed
    fastqc.patch ... Passed
==> Removing existing $srcdir/ directory...
==> Extracting sources...
  -> Extracting fastqc-0.12.1 with bsdtar
==> Starting prepare()...
patching file build.xml
==> Sources are ready.
fastqc-0.12.1-2: parsing pkg list...
==> Making package: fastqc 0.12.1-2 (Wed 26 Apr 2023 10:47:16 AM EEST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> WARNING: Using existing $srcdir/ tree
==> Removing existing $pkgdir/ directory...
==> Starting build()...
Buildfile: /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/build.xml

build-subprojects:

init:
    [mkdir] Created dir: /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/bin
     [copy] Copying 59 files to /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/bin

build-project:
     [echo] FastQC: /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/build.xml
    [javac] Compiling 138 source files to /home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/bin
    [javac] javac: invalid target release: 11
    [javac] Usage: javac <options> <source files>
    [javac] use -help for a list of possible options

BUILD FAILED
/home/mehrad/.cache/paru/clone/fastqc/src/FastQC-0.12.1/build.xml:36: Compile failed; see the compiler error output for details.

Total time: 0 seconds
==> ERROR: A failure occurred in build().
    Aborting...
error: failed to build 'fastqc-0.12.1-2':
error: packages failed to build: fastqc-0.12.1-2
```
 
 </details>

**Desktop (please complete the following information):**
 - Desktop Enviroment: KDE Plasma v5.27.4
 - Linux Kernel: 6.1.25-1-MANJARO
 - Package Version: [e.g. 22]

**Additional context**
--not applicable--

### PR DESCRIPTION
**Pull request by pekkarr**
## Involved packages

 - fastqc

## Involved issue

Close #130

## Details
- [x] Tested in the local machine (largest 16G RAM) and it is passed without any issue
- [x] Fix the Packages
  - [x] PKGBUILD

## Additional Note

@mmahmoudian

As said in the bug report, `fastqc` fails to build in a non-chroot environment, if the default java version (as set by `archlinux-java`) is older than 11. In addition to that, the application fails to launch if the default java is older than 11. This bug is not Manjaro specific, as it has been tested on Arch.

This patch makes the package use the latest available java version during build. The make dependency `java-environment>=11` guarantees that a recent one is available. During application startup the latest available java is chosen as well, if the default java is too old.

### CODE REVIEW

File: BioArchLinux/fastqc/fastqc.sh [hunk 1]
```diff
@@ -0,0 +1,15 @@
...
+  javaenv="$FASTQC_JAVA"
+else
+  default_java="$(archlinux-java get)"
+  if [ "$(echo "$default_java" | cut -d - -f 2)" -ge 11 ]; then
+    javaenv="$default_java"
+  else
+    # use latest available java
+    javaenv="$(archlinux-java status | tail -n +2 | cut -d ' ' -f 3 | sort -nk 2 -t - | tail -n 1)"
+  fi
+fi
```
Comment (sukanka) [inline BioArchLinux/fastqc/fastqc.sh:13]: how about changing them to this?
```shell
default_java="$(archlinux-java get)"
javaenv="${FASTQC_JAVA:-${default_java}}"
if [ "$(echo $javaenv|grep -Po '\d+')" -lt 11 ]; then
    # use latest available java
    latest_installed_java="$(archlinux-java status | tail -n +2 | cut -d ' ' -f 3 | sort -nk 2 -t - | tail -n 1)"
    if [ "$(echo $latest_installed_java|grep -Po '\d+')" -ge 11]; then
        javaenv="${latest_installed_java}"
    else
        echo "ERROR: No Java 11 or higher installed. Please install Java 11 or higher and try again."
        exit 1
    fi
fi
```

**Comment by sukanka** [comment]
Also, it would be better to add a post-install script to inform the users that they can set the java environment used in this program.

**Comment by pekkarr** [comment]
> it would be better to add a post-install script to inform the users that they can set the java environment used in this program

99.9% of users won't need this feature, since a suitable java is always selected automatically. I think it's unnecessary to add a post-install script because of that. The 0.1% that want to set `FASTQC_JAVA` can read the startup script.

**Review by sukanka — APPROVED** [review]

**Comment by hubutui** [comment]
Currently, the oldest jdk provided by ArchLinux is jdk8. Do we need to make sure every java app startup script should work with jdk8? It would be a tough job.

**Comment by pekkarr** [comment]
We can fix those if we get bug reports of them, otherwise I think it's too much work to check them all.

The basic principles would be like this:
- If a package depends on `java-runtime` without version requirements, it works with every officially supported java and should use the default java.
- If a package depends on `java-runtime=x`, then it should have a startup script that always selects that java version regardless of what is the default java on the system.
- If a package depends on `java-runtime>=x`, then it should use the default java if it's recent enough, and otherwise use the latest installed java.

However, I'm not sure how official packages handle this. If they have a different approach, we could follow that too.
